### ISSUE TITLE
Request for a none params integration request which is on dubbo protocol failed

### ISSUE THREAD

**Issue by MasterKenway** [apache/dubbo-go-pixiu#240]
**What happened**:
Request for a none params integration request which is on dubbo protocol failed
**What you expected to happen**:
fix it
**How to reproduce it (as minimally and precisely as possible)**:

In `samples/dubbogo/simple/query/`

add below function  for `userDB`
```
func (db *userDB) GetAllUsers() ([]*User, error) {
	var users []*User //nolint:prealloc
	if len(db.nameIndex) == 0 {
		return users, errors.New("no users")
	}

	for _, user := range db.nameIndex {
		users = append(users, user)
	}
	return users, nil
}
```

add below function for `UserProvider`
```
func (u *UserProvider) GetAllUsers(_ context.Context) ([]*User, error) {
	return cache.GetAllUsers()
}
```

add below config for `pixiu/api_config.yml`
```
  - path: '/api/v1/test-dubbo/getAll'
    type: restful
    description: user
    methods:
      - httpVerb: GET
        onAir: true
        timeout: 100s
        inboundRequest:
          requestType: http
        integrationRequest:
          requestType: dubbo
          applicationName: "UserService"
          interface: "com.dubbogo.pixiu.UserService"
          method: "GetAllUsers"
          group: "test"
          version: 1.0.0
          clusterName: "test_dubbo"
```

this example will lead to null pointer panic

**Anything else we need to know?**:
