### ISSUE TITLE
about pixiu cors config 

### ISSUE THREAD

**Issue by NyxRin** [apache/dubbo-go-pixiu#386]
I built a pixiu gateway to support Http access to dubbo service, and found that the OPTIONS request reported an error when configuring cross-domain. 
POST request is worked
This is my config in http_filters：
- name: dgp.filter.http.cors
  config:
    allow_origin:
      - 4970-27-156-220-138.ngrok.io:80
    allow_methods: ""
    allow_headers: ""
    expose_headers: ""
    max_age: ""
    allow_credentials: false

**What happened**:
13:12
2022-03-30T13:11:51.498+0800  ERROR  http/manager.go:90  ServeHTTP Requested URL /manga/game/manga-game/user/get not found
github.com/apache/dubbo-go-pixiu/pkg/common/http.(*HttpConnectionManager).ServeHTTP
  /Users/zhengchen/GolandProjects/dubbo-go-pixiu/pkg/common/http/manager.go:90
github.com/apache/dubbo-go-pixiu/pkg/filterchain.NetworkFilterChain.ServeHTTP
  /Users/zhengchen/GolandProjects/dubbo-go-pixiu/pkg/filterchain/network_filter_chain.go:45
github.com/apache/dubbo-go-pixiu/pkg/listener/http.(*DefaultHttpWorker).ServeHTTP
  /Users/zhengchen/GolandProjects/dubbo-go-pixiu/pkg/listener/http/http_listener.go:146
net/http.HandlerFunc.ServeHTTP
  /opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047
net/http.(*ServeMux).ServeHTTP
  /opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:2425
net/http.serverHandler.ServeHTTP
  /opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:2879
net/http.(*conn).serve
  /opt/homebrew/Cellar/go/1.17.6/libexec/src/net/http/server.go:1930

**Comment by baerwang** [comment]
use this config file try

```yaml
      filter_chains:
          filters:
            - name: dgp.filter.httpconnectionmanager
              config:
                route_config:
                  routes:
                    - match:
                        prefix: "/user"
                        methods:
                          - GET
                          - OPTIONS
                      route:
                        cluster: "user"
                        cluster_not_found_response_code: 505
                http_filters:
                  - name: dgp.filter.http.cors
                    config:
                      allow_origin:
                        - api.dubbo.com
                      allow_methods: ""
                      allow_headers: ""
                      expose_headers: ""
                      max_age: ""
                      allow_credentials: false
```
