### ISSUE TITLE
Pixiu Control Plane Support Service Mapping

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo-go-pixiu#485]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by mark4z** [comment]
I’m working on it

**Comment by AlbumenJ** [comment]
映射的逻辑是提供一个 com.example.DemoInterface => demo-application 的查找逻辑

涉及的接口样例如下：
set(interfaceName string, appName string)
get(interfaceName string) List
watch(interfaceName string) Obserable<List>

需要定义新的 proto，绑定在和 xds 同样的 grpc  Chanel

**Comment by yqxu** [comment]
I’m working on it

**Comment by mark4z** [comment]
对于基本的服务网格体系，首选的也是目前可以优先实现的选项是存储至k8s的注册中心。对此唯一的方式是创建一条该类型的CRD（k8s不允许执行操作其集群的etcd），然后自定义controller，通过informer来监听资源变动，大部分代码都可以用工具生成。

**Comment by mark4z** [comment]
借助目前xds的渠道可以较为简单地推送至各个dubbo服务，借助CRD可以较为简单地实现com.example.DemoInterface级别的增量，但内部app name list的增量，直观的方式是由control pannel缓存当前客户端的当前列表，但对control pannel压力很大，要考虑这个级别的增量是否是必要的。cc @AlbumenJ

**Comment by AlbumenJ** [comment]
> 借助目前xds的渠道可以较为简单地推送至各个dubbo服务，借助CRD可以较为简单地实现com.example.DemoInterface级别的增量，但内部app name list的增量，直观的方式是由control pannel缓存当前客户端的当前列表，但对control pannel压力很大，要考虑这个级别的增量是否是必要的。cc @AlbumenJ

control pannel 缓存就可以，数据量不会特别大

**Comment by mark4z** [comment]
> > 借助目前xds的渠道可以较为简单地推送至各个dubbo服务，借助CRD可以较为简单地实现com.example.DemoInterface级别的增量，但内部app name list的增量，直观的方式是由control pannel缓存当前客户端的当前列表，但对control pannel压力很大，要考虑这个级别的增量是否是必要的。cc @AlbumenJ
> 
> control pannel 缓存就可以，数据量不会特别大
okay

**Comment by mark4z** [comment]
初版CRD
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicenamemappings.networking.dubbo.io
spec:
  group: networking.dubbo.io
  scope: Namespaced
  names:
    kind: ServiceNameMapping
    plural: servicenamemappings
    singular: servicenamemapping
    shortNames:
      - snp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: >-
                it's the spec of Service Name Mapping, which is used to map the interface name 
                to the application name in application discovery.
              type: object
              properties:
                interfaceName:
                  type: string
                applicationName:
                  type: array
                  items:
                    type: string
            status:
              type: object
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: { }
```
