### ISSUE TITLE
httpfilter loadbalancer does not work when it has spaces between multiple urls

### ISSUE THREAD

**Issue by nicktming** [apache/dubbo-go-pixiu#512]
api-config.yaml 
```
name: pixiu
description: pixiu sample
resources:
  - path: 'xxx'
    ...
    methods:
      - httpVerb: POST
        ...
        integrationRequest:
          ...
          url: "x.x.x.1:20005, x.x.x.2:20005"

```

**What would you like to be added**:

problem: 
- it works well if url is 'x.x.x.1:20005,x.x.x.2:20005'
- it does not work well if url is 'x.x.x.1:20005, x.x.x.2:20005', since it will get a url named ' x.x.x.2:20005' , and expected url is 'x.x.x.2:20005' which does not have a space;

code comes from /pixiu/pkg/filter/http/loadbalancer/loadbalancer.go  
```
func (f *Filter) Decode(c *contexthttp.HttpContext) filter.FilterStatus {
	allInstances := strings.Split(c.GetAPI().IntegrationRequest.HTTPBackendConfig.URL, ",")
	idx := rand.Int31n(int32(len(allInstances)))
	c.Api.IntegrationRequest.HTTPBackendConfig.URL = allInstances[idx]
	return filter.Continue
}
```

it could be enhanced as follows:
```
c.Api.IntegrationRequest.HTTPBackendConfig.URL = strings.TrimSpace(allInstances[idx])
```

**Why is this needed**:

easy to use
