### ISSUE TITLE
使用pixiu自动装配如果访问无参数方法会提示参数数量不匹配

### ISSUE THREAD

**Issue by yangyy93** [apache/dubbo-go-pixiu#617]
**What happened**:
我刚刚开始接触dubbo协议，在使用pixiu测试http转dubbo协议访问dubbo服务的过程中发现了这个问题，
我使用的是dubbo-go-pixiu-sample的nacos测试，并为服务增加了一个新的无参数方法，使用新得测试用例后报错`client call err: the number of args(=1) is not matched with "GetUserByNameTestNoArgs" method`
以下是我使用的pixiu启动文件
```
---
static_resources:
  listeners:
    - name: "net/http"
      protocol_type: "HTTP"
      address:
        socket_address:
          address: "0.0.0.0"
          port: 8881
      filter_chains:
          filters:
            - name: dgp.filter.httpconnectionmanager
              config:
                route_config:
                  routes:
                    - match:
                        prefix: "*"
                http_filters:
                  - name: dgp.filter.http.apiconfig
                    config:
                      dynamic: true
                      dynamic_adapter: test
                  - name: dgp.filter.http.dubboproxy
                    config:
                      dubboProxyConfig:
                        registries:
                          "nacos":
                            protocol: "nacos"
                            timeout: "3s"
                            address: "127.0.0.1:8848"
                            username: nacos
                            password: nacos
                            group: test-group
                            namespace: test-namespace
  adapters:
    - id: test
      name: dgp.adapter.dubboregistrycenter
      config:
        registries:
          "nacos":
            protocol: nacos
            address: "127.0.0.1:8848"
            timeout: "5s"
            username: nacos
            password: nacos
            group: test-group
            namespace: test-namespace
```
新增的方法是这个：
```
func (u *UserProvider) GetUserByNameTestNoArgs(ctx context.Context) (*User, error) {
	fmt.Printf("Req GetUserByNameTestNoArgs")
	// get from cache directly
	r, ok := cache.GetByName("tc")
	if ok {
		fmt.Printf("Req GetUserByNameTestNoArgs result: %#v \n", r)
		return r, nil
	}
	return nil, nil
}
```
我的测试步骤是按照readme.md中的步骤
```
./start.sh prepare nacos
./start.sh startServer nacos
./start.sh startPixiu nacos 
./start.sh startTest nacos
```
在这个分支上运行上述命令即可复现该问题
https://github.com/yangyy93/dubbo-go-pixiu-samples/tree/test/dubbogo/simple

![image](https://github.com/apache/dubbo-go-pixiu/assets/30279937/a1ea994c-71ac-4b37-8dd8-3bdd68292a4c)

如果是我的某些配置没有配置好出现的该问题也请告知，感谢各位大佬。
