### ISSUE TITLE
bug: The timeout parameter in config does not take effect

### ISSUE THREAD

**Issue by Similarityoung** [apache/dubbo-go-pixiu#673]
**What happened**:

The timeout parameter in config does not take effect

```
      config:
        idle_timeout: "5s"
        read_timeout: "5s"
        write_timeout: "5s"
```
